---
title: "Prepare dependent variable"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
```

# Checks

```{r check crs, include=FALSE, eval=FALSE}
list.files(here("data","qc"), pattern = "nin.shp", recursive = TRUE) %>% 
  map(~ st_read(here("data","qc",.x), quiet = TRUE) %>% 
        st_crs()) %>% 
  map_int(~ .$epsg) %>% 
  table()
list.files(here("data","qc"), pattern = "wildlings-height.shp", recursive = TRUE) %>% 
  map(~ st_read(here("data","qc",.x), quiet = TRUE) %>% 
        st_crs()) %>% 
  map_int(~ .$epsg) %>% 
  table()
```

```{r check heights}
hgtfiles <- list.files(here("data","qc"), pattern = "height.shp", recursive = TRUE)
hgtpts <- hgtfiles %>% 
  set_names(gsub("/wildlings-height.shp","",.)) %>% 
  map(~ st_read(here("data","qc",.x), quiet = TRUE))
        
hgts <- hgtpts %>% 
  map_dfr(st_drop_geometry, .id = "file") %>% 
  select(file, count, hgt, hgt_assume) %>% 
  mutate(count = replace_na(count, 1),
         hgt_assume = replace_na(hgt_assume, 0)) %>% 
  tibble()
summary(hgts)
all.equal(hgts$count, as.integer(hgts$count))
all.equal(hgts$hgt, as.integer(hgts$hgt))
slice(hgts, which(hgts$hgt != as.integer(hgts$hgt)))
pull(hgts, hgt_assume) %>% unique()

filter(hgts, hgt_assume == 0) %>% 
  ggplot(aes(hgt, file)) + geom_boxplot() + labs(title = "Individually measured heights")
filter(hgts, hgt < 30) %>% 
  arrange(file, hgt) %>% 
  print(n = nrow(.))

filter(hgts, hgt_assume == 1) %>% 
  ggplot(aes(hgt, file)) + geom_boxplot() + labs(title = "Indirectly measured heights")

hgts %>% 
  uncount(weights = count) %>% 
  group_by(file) %>% 
  summarize(unmeasured = sum(is.na(hgt)),
            n = n(),
            propunmeasured = unmeasured/n()) %>% 
  ggplot(aes(propunmeasured, file)) + geom_col() + 
  geom_text(aes(label = n), hjust = 0) +
  labs(title = "Proportion of unmeasured heights",
       subtitle = "Labelled with total number of wildlings")
hgts %>% 
  uncount(weights = count) %>% 
  summarise(sum(is.na(hgt))/n())
```

# Point geometries with heights

```{r}
standardcrs <- st_crs(25833) 
hgtfiles <- list.files(here("data","qc"), pattern = "height.shp", recursive = TRUE)
hgtpts <- hgtfiles %>% 
  set_names(gsub("/wildlings-height.shp","",.)) %>% 
  map(~ st_read(here("data","qc",.x), quiet = TRUE))
str(hgtpts, 1)

hgtpts25832 <- hgtpts %>% 
  map(st_transform, crs = standardcrs) %>% 
  bind_rows(.id = "file") %>% 
  mutate(species = gsub("/.*", "", file),
         locality =  gsub(".*/", "", file),
         count = as.integer(replace_na(count, 1)),
         hgt_assume = as.logical(replace_na(hgt_assume, 0))) %>% 
  filter(hgt >= 30 | is.na(hgt)) %>% 
  select(species, locality, count, hgt, hgt_assume)
```

# Height stratification

```{r}
hgtpts25832 %>% 
  group_by(species) %>% 
  uncount(weights = count) %>% 
  summarise(lowerquartilehgt = quantile(hgt, 0.25, na.rm = TRUE),
            upperquartilehgt = quantile(hgt, 0.75, na.rm = TRUE))

classlimits <- tribble(
  ~class, ~lower, ~upper,
       1,     30,     80,
       2,     80,    200,
       3,    200,  10000
)
```

# Height assignment

```{r}
assign_hgts_singleseed <- function(hgtpts, seed) {
  pool <- na.omit(hgtpts$hgt)
  set.seed(seed)
  mutate(hgtpts,
         randomseed = seed,
         hgt_random = sample(pool, size = nrow(hgtpts), replace = TRUE),
         hgt_assign = is.na(hgt),
         hgt = ifelse(hgt_assign, hgt_random, hgt)) %>% 
    select(species, randomseed, locality, hgt, hgt_assume, hgt_assign, geometry)
}

assign_heights <- function(hgtptssplit, nrseeds = 5) {
  map(seq_len(nrseeds), ~ assign_hgts_singleseed(hgtptssplit, .)) %>% 
    bind_rows()
}

hgtptssplit <- hgtpts25832 %>% 
  uncount(weights = count) %>%
  group_by(species, locality) %>% 
  group_split()

DV <- map(hgtptssplit, assign_heights) %>% 
  bind_rows() %>% 
  mutate(hgtclass = case_when(
    hgt < classlimits$upper[1] ~ classlimits$class[1],
    hgt >= classlimits$lower[2] & hgt < classlimits$upper[2] ~ classlimits$class[2],
    hgt >= classlimits$lower[3] ~ classlimits$class[3]),
    .before = locality)

DV %>%
  mutate(file=paste(species, locality, sep = "/")) %>%
  ggplot(aes(x=hgt, y=file, color = hgt_assign)) + geom_boxplot() +
  facet_grid(cols = vars(randomseed))
```

```{r}
saveRDS(DV, here("output","dependentVar.rds"))
```

```{r sessionInfo}
sessionInfo()
```