---
title: "Prepare independent variables"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
library(units)
source(here("R","locality-functions.R"))
```

# Checks

```{r check topology, include=FALSE, eval=FALSE}
ninfiles <- list.files(here("data","qc"), pattern = "nin.shp", recursive = TRUE)
for (i in ninfiles) {
  shp <- st_read(here("data","qc",i), quiet = TRUE) %>% 
    st_zm(drop = TRUE, what = "ZM")
  if (!all(st_is_valid(shp))) {
    message(paste(i, "contains invalid topology"))
  }
  message(i)
}
```

```{r check crs, include=FALSE, eval=FALSE}
list.files(here("data","qc"), pattern = "nin.shp", recursive = TRUE) %>% 
  map(~ st_read(here("data","qc",.x), quiet = TRUE) %>% 
        st_crs()) %>% 
  map_int(~ .$epsg) %>% 
  table()
list.files(here("data","qc"), pattern = "wildlings-height.shp", recursive = TRUE) %>% 
  map(~ st_read(here("data","qc",.x), quiet = TRUE) %>% 
        st_crs()) %>% 
  map_int(~ .$epsg) %>% 
  table()
```

# Grid cells with covariates

WALD seed shadows produced separately because of long computation time. 

```{r cells}
standardcrs <- st_crs(25833) 
pairing <- read_csv(here('data','codetype-pairing.csv'))

species <- list.files(here("data","qc"))

bylocality <- list()

for (j in species) { # j <- species[1]
  message(j)
  localities <- list.files(here("data","qc",j))

  for (i in localities) { # i <- localities[1]
    message(i)
    nin <- st_read(here("data","qc",j,i,"nin.shp"), quiet = TRUE) %>% 
      st_transform(standardcrs) %>% 
      as_tibble() %>% st_as_sf() %>% 
      mutate(code = as.character(code), type = NULL) %>% 
      left_join(pairing, by = "code")
    grd <- make_grid(nin, gridres = 10)
    
    grd <- add_dummies_to_grid(grd, nin, field = type) %>% 
      as_tibble() %>% st_as_sf()
    grd <- grd %>% 
      mutate(rsum = rowSums(st_set_geometry(grd, NULL), na.rm = TRUE)) %>% 
      filter(rsum >= 0.5) %>% 
      select(-rsum) %>% 
      mutate_at(vars(-geometry), round, digits = 3) 
    
    source <- st_read(here("data","qc",j,i,"source_polygon.shp"), quiet = TRUE) %>% 
      st_zm(drop = TRUE, what = "ZM")
    source <- mutate(source, nsources = st_area(source) %>% 
                       `/`(100) %>% # 1 sources per 100m2 (gridres 10x10m)
                       drop_units() %>% 
                       round())
    source.nonz <- filter(source, nsources > 0)
    set.seed(42)
    sources <- st_sample(source.nonz, source.nonz$nsources, type = "hexagonal") %>% st_sf()
    grd <- add_seeds_ExP(grd, sources)
    
    grd <- add_seeds_WALD(grd, raster::raster(here("data","qc",j,i,"wald.tif")))
    
    grd <- mutate(grd, seeds.ExP = case_when(
      is.na(seeds.WALD) ~ NA_real_,
      TRUE ~ seeds.ExP
    )) 

    if (file.exists(here("data","qc",j,i,"dtm1","data","dtm1.tif"))) {
      dtm <- raster::raster(here("data","qc",j,i,"dtm1","data","dtm1.tif"))
    } else {
      dtm <- raster::raster(here("data","qc",j,i,"dtm10","data","dtm10.tif"))
    }
    grd <- add_relative_elevation(grd, filter(source, FID == 0), dtm)
    
    bylocality[[j]][[i]] <- grd
  }
}
```

```{r aggregated by species}
str(bylocality, 2)
collated <- bylocality %>% 
  map(bind_rows, .id = "locality") %>% 
  bind_rows(.id = "species")

summary(collated)
excluded <- c("species", "locality", "seeds.ExP", "seeds.WALD", "relelev")
collated <- collated %>% 
  mutate(across(!all_of(excluded), ~ replace_na(.x, replace = 0)))
summary(collated)
```

```{r locality covariates}
localities <- read_csv(here("output", "localities-modified.csv")) # see 'locality-WALD.Rmd' 

locs <- localities %>% 
  select(locality, species, age.at.registration, utm33.easting, utm33.northing) %>% 
  st_as_sf(coords=c("utm33.easting", "utm33.northing"), crs = 25833) %>% 
  as("Spatial")

chelsa <- raster::stack(here("data","raw","CHELSA","CHELSA_bio_1.tif"),
                        here("data","raw","CHELSA","CHELSA_bio_19.tif"))
jointable <- raster::extract(chelsa, locs, sp = TRUE) %>% 
  st_as_sf() %>% st_set_geometry(NULL) %>% as_tibble() %>% 
  rename(age = age.at.registration, bio01 = CHELSA_bio_1, bio19 = CHELSA_bio_19) %>% 
  mutate(locality = tolower(locality))
anyNA(jointable)

collated <- collated %>% 
  left_join(jointable, by = c("species", "locality")) %>%
  relocate(species, locality, age, bio01, bio19, 
           seeds.ExP, seeds.WALD, relelev, `plantation forest`) %>% 
  relocate(geometry, .after = last_col())

saveRDS(collated, here("output","independentVars.rds"))

localities %>% 
  mutate(locality = tolower(locality)) %>% 
  left_join(jointable, by = c("species", "locality")) %>% 
  write_csv(here('output', 'localities-modified.csv'))
```

```{r sessionInfo}
sessionInfo()
```