---
title: "Join dependent--independent variables"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
library(units)
```

# Height stratification

```{r}
hgtpts <- readRDS(here("output","dependentVar.rds"))

hgtpts %>% 
  group_by(species) %>% 
  uncount(weights = count) %>% 
  summarise(lowerquartilehgt = quantile(hgt, 0.25, na.rm = TRUE),
            upperquartilehgt = quantile(hgt, 0.75, na.rm = TRUE))
hgtpts %>% 
  group_by(species) %>% 
  uncount(weights = count) %>% 
  summarise(quantile80cm = ecdf(hgt)(80),
            quantile250cm = ecdf(hgt)(250))

classlimits <- tribble(
  ~class, ~lower, ~upper,
       1,     30,     80,
       2,    250,  10000
)
```

# Height assignment

```{r}
hgtptssplit <- hgtpts %>% 
  uncount(weights = count) %>%
  group_by(species, locality) %>% 
  group_split()

set.seed(42)
hgtptsi <- hgtptssplit %>%
  map(~ mutate(., 
               hgt_random = sample(na.omit(hgt), size = nrow(.), replace = TRUE),
               hgt_assign = is.na(hgt),
               hgt = ifelse(hgt_assign, hgt_random, hgt))) %>% 
  bind_rows() %>% 
  select(species, locality, hgt, hgt_assume, hgt_assign, geometry)
tail(hgtptsi)

hgtptsi %>% 
  mutate(file=paste(species, locality, sep = "/")) %>% 
  ggplot(aes(x=hgt, y=file, color = hgt_assign)) + geom_boxplot()

assign_random_height <- function(seed, DV) { #seed <- 42; DV <- filter(hgtpts, species == "Larix")
  DVsplit <- DV %>% 
    uncount(weights = count) %>%
    group_by(locality) %>% 
    group_split()
  set.seed(seed)
  DVassigned <- DVsplit %>%
    map(~ mutate(., 
                 hgt_random = sample(na.omit(hgt), size = nrow(.), replace = TRUE),
                 hgt_assign = is.na(hgt),
                 hgt = ifelse(hgt_assign, hgt_random, hgt))) %>% 
    bind_rows() %>% 
    select(species, locality, hgt, hgt_assume, hgt_assign, geometry)
  return(DVassigned)
}
```

```{r}
iv <- readRDS(here("output","independentVars.rds"))

for (i in unique(hgtpts$species)) { # i <- "Larix"
  IV <- filter(iv, species == i)
  DV <- filter(hgtpts, species == i)
  DV <- 1:5 %>% 
    map(assign_random_height, DV = DV)
  
}

group_split(iv, species)

hgtclasses <- classlimits %>% 
  pmap(~ filter(hgtptsi, hgt >= ..2, hgt <= ..3))


```

Pseudocode:
1. Load independentVars
2. Separate by species (x3)
3. spatial "left_join" of independentVars to dependentVar (x2 hgtclasses) (see *add_wildlings* function)
4. save as list with species at first level, followed by height classes at lower level, (followed by set.seed at lower level?)

```{r sessionInfo}
sessionInfo()
```