---
title: "Locality maps"
output: 
  html_document:
    toc: true
    toc_float: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(here)
library(tidyverse)
library(sf)
source(here("R","functions.R"))
```

```{r}
IV <- readRDS(here("output","independentVars.rds")) %>% 
  st_as_sf()
DV <- readRDS(here("output","dependentVar.rds"))
```

Only plotting with randomseed == 2. Other randomseeds will have slightly different distributions of wildlings across height classes (but the same total number of wildlings).

```{r}
DV <- filter(DV, randomseed == 2)
```

```{r results='asis'}
for (i in unique(DV$species)) { # i <- "Larix"
  cat('\n#', i, '\n')
  localities <- filter(DV, species == i) %>% 
    pull(locality) %>% 
    unique()
  for (j in localities){ # j <- "anisdal"
    cat('\n##', j, '\n')
    DVij <- filter(DV, species == i, locality == j)
    IVij <- filter(IV, species == i, locality == j)
    present <- IVij %>% 
      st_drop_geometry() %>% 
      select(9:last_col()) %>% 
      colSums(na.rm=TRUE) %>% 
      enframe() %>% 
      arrange(desc(value)) %>% 
      filter(value > 0) %>% 
      pull(name)
    mp <- 3 + length(present)
    IVij %>% 
      select(seeds.WALD, seeds.ExP, relelev, all_of(present)) %>% 
      plot(max.plot = mp)
    add_wildlings(IVij, filter(DVij, hgtclass==2)) %>% 
      select(wildlings) %>% 
      plot(main = 'height \u2265 100 cm')      
    add_wildlings(IVij, DVij) %>% 
      select(wildlings) %>% 
      plot(main = 'height \u2265 30 cm')      
    cat('\n')
  }
}
```

```{r sessionInfo}
sessionInfo()
```