---
title: "Locality WALD"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r jobs script, eval=FALSE}
knitr::purl(input = here('reports','locality-WALD.Rmd'),
            output = here('reports','locality-WALD.R'))
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
library(units)
source(here("R","locality-functions.R"))
source(here("R","dispersal-functions.R"))
source(here("R","SkarpaasShea_2007.R"))
```

```{r species dispersal traits}
traits <- tribble(
  ~species, ~terminal.velocity, ~dispersal.season,
  "Larix", 1.0, c(12,1:5), # After Sandvik 2012 (for L. decidua), and Sullivan 1994 (for L. decidua)
  "P.abies", 0.58, c(11:12,1:5), # After Sandvik 2012 (but see Kaliniewicz et al. 2018), and Sullivan 1994
  "P.contorta", 0.82, c(9:12), # After Sandvik 2012
  "P.sitchensis-lutzii", 0.94, c(10:12,1:2) # After Sandvik 2012 (but see Kaliniewicz et al. 2018), and Harris 1990
)
```

```{r localities table}
loc.tab <- read_csv(here("data","localities.csv"))
filter(loc.tab, is.na(age.at.registration))
loc.tab$age.interpolated <- FALSE
# Need age to interpolate height
HaakoeyaAge <- loc.tab %>% 
  filter(species == "P.sitchensis-lutzii", county %in% c("Troms","Nordland")) %>% 
  pull(age.at.registration) %>% 
  mean(na.rm = TRUE) %>% 
  round()
loc.tab[loc.tab$locality=="Haakoeya", "age.at.registration"] <- HaakoeyaAge 
loc.tab[loc.tab$locality=="Haakoeya", "age.interpolated"] <- TRUE
filter(loc.tab, is.na(age.at.registration))

filter(loc.tab, is.na(height.source))
loc.tab$height.interpolated <- FALSE
for (i in which(is.na(loc.tab$height.source))) {
  loc.tab[i, "height.source"] <- interpolate_height(loc.tab[i,], loc.tab)
  loc.tab[i, "height.interpolated"] <- TRUE
}

g <- ggplot(loc.tab, aes(x=age.at.registration, y=height.source, color=species))
g + geom_point()
```

```{r, eval=FALSE}
write_csv(loc.tab, here('output', 'localities-modified.csv'))
```

```{r wind data}
norabcxy <- st_read(here("data","raw","NORA10","NORA10BCsites.shp")) %>% 
  st_set_crs(25833)
norabc <- read_csv(here("data","raw","NORA10","NORA10BCwind.csv"))

noraxy <- st_read(here("data","raw","NORA10","NORA10sites.shp")) %>% 
  st_set_crs(25833)
nora <- read_csv(here("data","raw","NORA10","NORA10wind.csv"))

eklimaxy <- st_read(here("data","raw","eKlima","EKLIMAsites.shp")) %>% 
  st_set_crs(25833)
eklima <- read_csv(here("data","raw","eKlima","EKLIMAwind.csv"))

sector.breaks <- seq(0, 360, by=20)
```

```{r unique types, eval=FALSE}
ninfiles <- list.files(here("data","qc"), pattern = "nin.shp", recursive = TRUE)
codes <- map(ninfiles, ~ st_read(here("data","qc",.), quiet = TRUE) %>% 
               pull(code) %>% 
               as.character())
map(codes, ~ any(is.na(.))) %>% 
  unlist() %>% 
  which()
codes <- flatten_chr(codes) %>% 
  unique()
codes[order(substring(codes, 1, 1), as.numeric(substring(codes, 2)))]
```

```{r code-type pairing}
pairing <- read_csv(here('data','codetype-pairing.csv'))
```

```{r vegetation height}
types <- read_csv(here('data','types.csv'))
vegheights <- types %>% 
  group_by(type) %>% 
  summarize(vegheight = mean(vegheight))
```

```{r}
rlogging::SetLogFile(base.file="locality-WALD.log", folder=here('reports'))
```

```{r WALD seed shadows}
species <- list.files(here("data","qc"))

for (i in species[1]) { # i <- species[1]
  message(i)
  terminal.velocity <- filter(traits, species == i) %>% 
    pull(terminal.velocity)
  dispersal.season <- filter(traits, species == i) %>% 
    pull(dispersal.season) %>% 
    unlist()
  
  localities <- list.files(here("data","qc",i))
  
  for (j in localities[1]) { # j <- localities[1]
    message(j)
    nin <- st_read(here("data","qc",i,j,"nin.shp"), quiet = TRUE) %>% 
      as_tibble %>% st_as_sf() %>% 
      mutate(code = as.character(code), type = NULL) %>% 
      left_join(pairing, by = "code") %>% 
      filter(type != "plantation forest")
    grd <- make_grid(nin, gridres = 10)
    grd <- add_dummies_to_grid(grd, nin, field = type) %>% 
      as_tibble() %>% st_as_sf()
    grd <- grd %>% 
      mutate(rsum = rowSums(st_set_geometry(grd, NULL), na.rm = TRUE)) %>% 
      filter(rsum >= 0.5) %>% 
      select(-rsum) %>% 
      mutate_at(vars(-geometry), round, digits = 3) 
    vegheights.j <- vegheights %>% 
      filter(type %in% colnames(grd)) %>% 
      arrange(match(type, colnames(grd))) %>% 
      pull(vegheight)
    grd <- grd %>%
      mutate(normalizer = st_set_geometry(., NULL) %>% rowSums(., na.rm = TRUE))
    grd <- grd %>% 
      mutate(vegheight = grd %>% 
               st_set_geometry(NULL) %>%
               select(-normalizer) %>% 
               replace(is.na(.), 0) %>% 
               as.matrix() %*% vegheights.j %>% 
               as.vector())
    grd <- grd %>%
      mutate(vegheight = vegheight / normalizer) %>% 
      select(-normalizer)
    grd.pts <- st_centroid(st_geometry(grd))

    source <- st_read(here("data","qc",i,j,"source_polygon.shp"), quiet = TRUE) 
    source <- mutate(source, nsources = st_area(source) %>% 
                       `/`(100) %>% # 1 source per 100m2 (gridres 10x10m)
                       drop_units() %>% 
                       round())
    source.nonz <- filter(source, nsources > 0) %>% 
      st_zm(drop = TRUE, what = "ZM")
    set.seed(42)
    sources <- st_sample(source.nonz, source.nonz$nsources, type = "hexagonal") %>% 
      st_sf() %>% 
      st_transform(st_crs(grd))
    height <- loc.tab %>% 
      mutate(locality = tolower(locality)) %>% 
      filter(species == i, locality == j) %>% 
      pull(height.source)
    
    grdxy <- grd[1,] %>%  st_transform(st_crs(eklimaxy)) # EPSG 25833
    eklima.near <- eklimaxy[st_nearest_feature(grdxy, eklimaxy), ]
    norabc.near <- norabcxy[st_nearest_feature(grdxy, norabcxy), ]
    nora.near <- noraxy[st_nearest_feature(grdxy, noraxy), ]
    if (st_distance(grdxy, eklima.near, by_element = TRUE) < set_units(2.5e3, "m")) {
      windobs <- filter(eklima, St.no == eklima.near$Stnr)
      x <- st_distance(grdxy, eklima.near, by_element = TRUE) %>% 
        `/`(1e3) %>% 
        round() 
      paste(i, j, paste0("eKlima station no. ", eklima.near$Stnr), 
            paste0(x," km away"),
            sep = ", ") %>% 
        rlogging::message()
    } else if (st_distance(grdxy, norabc.near, by_element = TRUE) < set_units(2.5e3, "m")) {
      windobs <- filter(norabc, SITE == norabc.near$site)
      x <- st_distance(grdxy, norabc.near, by_element = TRUE) %>% 
        `/`(1e3) %>% 
        round() 
      paste(i, j, paste0("NORA10BC site ", norabc.near$site), 
            paste0(x," km away"),
            sep = ", ") %>% 
        rlogging::message()
    } else if (st_distance(grdxy, eklima.near, by_element = TRUE) < set_units(10e3, "m")) {
      windobs <- filter(eklima, St.no == eklima.near$Stnr)
      x <- st_distance(grdxy, eklima.near, by_element = TRUE) %>% 
        `/`(1e3) %>% 
        round() 
      paste(i, j, paste0("eKlima station no. ", eklima.near$Stnr), 
            paste0(x," km away"),
            sep = ", ") %>% 
        rlogging::message()
    } else {
      windobs <- filter(nora, SITE == nora.near$site)
      x <- st_distance(grdxy, nora.near, by_element = TRUE) %>% 
        `/`(1e3) %>% 
        round()
      paste(i, j, paste0("NORA10 site ", nora.near$site), 
            paste0(x," km away"),
            sep = ", ") %>% 
        rlogging::message()
      }
    windobs <- windobs %>% 
      select(Mnth, DD, FF) %>% 
      filter(Mnth %in% dispersal.season) %>% 
      mutate(sector = cut(DD, sector.breaks, include.lowest = TRUE))
    # Assume probability of abscission is UNRELATED to wind speed (constant)
    sectors360 <- tibble(sector = unique(cut(0:360, sector.breaks, include.lowest = TRUE))) %>% 
      left_join(as.data.frame(prop.table(table(windobs$sector))), by=c('sector' = 'Var1'))
    set.seed(42)
    winds <- lapply(sectors360$sector, function(x) {
      filter(windobs, sector == x) %>% 
        sample_n(100, replace = TRUE, weight = NULL) %>% 
        pull(FF)
    })
    names(winds) <- sectors360$sector
  
    pb <- txtProgressBar(0, nrow(sources), style = 3)
    
    src.arr <- array(dim = c(nrow(grd), nrow(sources)))
    for (k in seq_along(sources$geometry)) { # k <- 1
      grd$sector <- assign_sectors(to = grd.pts, around = sources[k, ], 
                                   between = sector.breaks)
      distances.k <- as.numeric(st_distance(grd.pts, sources[k,]))
      sectors.k <- sectors360$sector[sectors360$sector %in% grd$sector]
  
      sec.arr <- array(dim = c(nrow(grd), length(sectors.k)))
      for (l in seq_along(sectors.k)) { # l <- 1
        vegheight <- grd %>% 
          filter(sector == sectors.k[l]) %>% 
          pull(vegheight) %>% 
          mean()
        distances.l <- distances.k
        distances.l[grd$sector != sectors.k[l]] <- NA
    
        wind.arr <- array(data = NA, dim = c(nrow(grd), 100))
        for (m in 1:100) {
          WALD <- parameterize_WALD(H = height, 
                                    Fm = terminal.velocity,
                                    Um = winds[[l]][m], 
                                    zm = 10, # 10 m above ground 
                                    h = vegheight)
          
          # Divisor below accounts for the fact that the WALD formulation used here (inverse gaussian dist) is the "dispersal DISTANCE kernel" (eq. 15.3 Nathan et al. 2012). 
          # 2πr reduces the probability density by spreading it across a 2D ring
          # nrow(sectors360) further reduces the probability density because we take only a fraction of the 2D ring (an arc)
          # Essentially, far cells are reduced relative to close cells, because the distance kernel is spread over a longer arc at distance.
          wind.arr[, m] <- WALD(distances.l) / (2*pi*distances.l*nrow(sectors360))
        }
        sec.arr[, l] <- sum_second_dim(wind.arr)
      }
      src.arr[, k] <- sum_second_dim(sec.arr, 
                                     sectors360$Freq[which(sectors360$sector %in% sectors.k)])
      setTxtProgressBar(pb, k)
    }      
    close(pb)
    
    grd <- mutate(grd, wald = sum_second_dim(src.arr))
    ras <- grd %>% 
      select(wald) %>% 
      as("Spatial") %>% 
      raster::rasterize(raster::raster(grd, resolution = 10), "wald")
    raster::writeRaster(ras, here("data","qc",i,j,"wald.tif"), overwrite = TRUE)
  }
}

```

```{r, eval=FALSE, include=FALSE}
slow <- raster::raster(here("data","qc","Larix","anisdal","wald10daa.tif"))
fast <- raster::raster(here("data","qc","Larix","anisdal","wald.tif"))
st <- raster::stack(slow, fast)
df <- raster::as.data.frame(st, na.rm=TRUE)
cor(df)
pairs(df)
```

```{r sessionInfo}
sessionInfo()
```