---
title: "Modeling"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(tidyverse)
library(glmmTMB)
```

```{r}
datlist <- readRDS(here("output","data.rds"))
```

# Larix

```{r}
dat <- datlist$Larix %>% 
  psycho::standardize(subset = list("seeds.WALD","seeds.ExP","age",
                                    "bio01","bio19","relelev"))
str(dat)
paste(names(dat), collapse = " + ")
```

```{r}
f1 <- formula("wildlings ~ seeds.WALD + age + bio01 + bio19 + relelev + cultivated + disturbed + T32 + fen + T34 + T13 + T4 + T2 + T1 + swamp + T30 + T18 + T27 + T17 + (1 | locality)")
m1 <- glmmTMB(f1, dat, family = "nbinom2", ziformula = ~1, verbose = TRUE)
# Warning messages:
# 1: In fitTMB(TMBStruc) :
# Model convergence problem; non-positive-definite Hessian matrix. See vignette('troubleshooting')
# 2: In fitTMB(TMBStruc) :
# Model convergence problem; singular convergence (7). See vignette('troubleshooting')
```

Perfectly separated: T18, T30, T2, T27, swamp, T13

```{r}
f2 <- formula("wildlings ~ seeds.WALD + age + bio01 + bio19 + relelev + cultivated + disturbed + T32 + fen + T34 + T4 + T1 + T17 + (1 | locality)")
m2 <- glmmTMB(f2, dat, family = "nbinom2", ziformula = ~1, verbose = TRUE)
summary(m2)
```


# P.abies


# P.contorta


# P.sitchensis


```{r sessionInfo}
sessionInfo()
```