---
title: "wildlings-NiN"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(sf)
library(units)
source(here("R","locality-functions.R"))
```

```{r unique types, eval=FALSE}
ninfiles <- list.files(here("data","qc"), pattern = "nin.shp", recursive = TRUE)
codes <- map(ninfiles, ~ st_read(here("data","qc",.), quiet = TRUE) %>% 
               pull(code) %>% 
               as.character())
map(codes, ~ any(is.na(.))) %>% 
  unlist() %>% 
  which()
codes <- flatten_chr(codes) %>% 
  unique()
codes[order(substring(codes, 1, 1), as.numeric(substring(codes, 2)))]
```

```{r grouping of types}
grouping <- tribble(
  ~code, ~group, ~vegheight,
  "T1", "T1", 0,
  "T2", "T2", 0.5,
  "T3", "T3", 0.5,
  "T4", "T4", 10,
  "T6", "T6", 0,
  "T12", "T12", 0.5,
  "T13", "T13", 0,
  "T16", "T16", 0.5,
  "T17", "T17", 0,
  "T18", "T18", 0,
  "T21", "T21", 0,
  "T24", "T24", 0.5,
  "T27", "T27", 0,
  "T29", "T29", 0,
  "T30", "T30", 10,
  "T31", "T31", 0.5,
  "T32", "T32", 0.5,
  "T33", "T33", 0.5,
  "T34", "T34", 0.5,
  "T35", "disturbed", 0,
  "T36", "disturbed", 0.5,
  "T37", "disturbed", 0,
  "T38", "plantation forest", 10,
  "T39", "disturbed", 0,
  "T40", "disturbed", 0,
  "T41", "cultivated", 0.5,
  "T42", "disturbed", 0,
  "T43", "disturbed", 0,
  "T44", "cultivated", 0.5,
  "T45", "cultivated", 0.5,
  "T35.T37.T39.T43", "disturbed", 0,
  "T35.T37", "disturbed", 0,
  "V1", "fen", 0,
  "V2", "swamp", 10,
  "V3", "bog", 0,
  "V4", "spring", 0,
  "V8", "swamp", 10,
  "V9", "fen", 0,
  "V10", "fen", 0,
  "V11", "disturbed", 0,
  "V12", "disturbed", 0,
  "V13", "disturbed", 0) 
```

```{r check topology, include=FALSE, eval=FALSE}
for (i in ninfiles) {
  shp <- st_read(here("data","qc",i), quiet = TRUE)
  if (!all(st_is_valid(shp))) {
    message(paste(i, "contains invalid topology"))
  }
}
```

```{r wildlings per polygon}
species <- list.files(here("data","qc"))

perNiN <- list()

for (j in species) { # j <- species[1]
  message(j)
  localities <- list.files(here("data","qc",j))

  for (i in localities) { # i <- localities[1]
    nin <- st_read(here("data","qc",j,i,"nin.shp"), quiet = TRUE) %>% 
      as_tibble %>% st_as_sf() %>% 
      mutate(code = as.character(code), group = NULL) %>% 
      left_join(grouping, by = "code")
    wildlings <- st_read(here("data","qc",j,i,"wildlings.shp"), quiet = TRUE)
    wildling.density <- calc_density_by_field(poly = nin, pts = wildlings, 
                                              field = group)
    perNiN[[j]][[i]] <- wildling.density
  }
}

perNiN.agg <- lapply(perNiN, function(x) {
  bind_rows(x) %>% 
    group_by(group) %>% 
    summarize(area = sum(area), n = sum(n)) %>% 
    mutate(density = n/area) %>%
    arrange(desc(density), desc(n), area) %>% 
    mutate(area = round(area), density = round(density, digits = 1))
})
```

```{r wildlings per polygon aggregated}
lapply(perNiN.agg, knitr::kable)
```

WALD seed shadows produced separately because of long computation time. 

```{r wildlings per cell}
species <- list.files(here("data","qc"))

percell <- list()

for (j in species) { # j <- species[1]
  message(j)
  localities <- list.files(here("data","qc",j))

  for (i in localities) { # i <- localities[1]
    message(i)
    nin <- st_read(here("data","qc",j,i,"nin.shp"), quiet = TRUE) %>% 
      as_tibble %>% st_as_sf() %>% 
      mutate(code = as.character(code), group = NULL) %>% 
      left_join(grouping, by = "code")
    grd <- make_grid(nin, gridres = 10)
    
    grd <- add_dummies_to_grid(grd, nin, field = group) %>% 
      as_tibble() %>% st_as_sf()
    grd <- grd %>% 
      mutate(rsum = rowSums(st_set_geometry(grd, NULL), na.rm = TRUE)) %>% 
      filter(rsum >= 0.5) %>% 
      select(-rsum) %>% 
      mutate_at(vars(-geometry), round, digits = 3) 
    
    source <- st_read(here("data","qc",j,i,"source_polygon.shp"), quiet = TRUE) 
    source <- mutate(source, nsources = st_area(source) %>% 
                       `/`(10) %>% # 10 sources per 100m2 (gridres 10x10m)
                       drop_units() %>% 
                       round())
    source.nonz <- filter(source, nsources > 0)
    set.seed(42)
    sources <- st_sample(source.nonz, source.nonz$nsources, type = "hexagonal") %>% st_sf()
    grd <- add_seeds_ExP(grd, sources)
    
    grd <- add_seeds_WALD(grd, raster::raster(here("data","qc",j,i,"wald.tif")))
    
    grd <- mutate(grd, seeds.ExP = case_when(
      is.na(seeds.WALD) ~ NA_real_,
      TRUE ~ seeds.ExP
    )) 

    if (file.exists(here("data","qc",j,i,"dtm1","data","dtm1.tif"))) {
      dtm <- raster::raster(here("data","qc",j,i,"dtm1","data","dtm1.tif")) %>% 
        raster::aggregate(fact = 2)
    } else {
      dtm <- raster::raster(here("data","qc",j,i,"dtm10","data","dtm10.tif"))
    }
    grd <- add_relative_elevation(grd, filter(source, FID == 0), dtm)
    
    wildlings <- st_read(here("data","qc",j,i,"wildlings.shp"), quiet = TRUE)
    grd <- add_wildlings(grd, wildlings)
    
    percell[[j]][[i]] <- select(grd, wildlings, everything())
  }
}

saveRDS(percell, here("output","percell-data.rds"))
```

```{r wildlings per cell aggregated}
percell <- readRDS(here("output","percell-data.rds"))

str(percell, 2)
percell <- map(percell, ~ map(., ~ st_set_geometry(., NULL)))
percell.agg <- map(percell, ~ map_dfr(., identity, .id = "locality"))
str(percell.agg, 1)
percell.agg

excluded <- c("wildlings", "locality", "seeds.ExP", "seeds.WALD", "relelev")
percell.agg <- map(percell.agg, function(x) {
  included <- names(x)[!(names(x) %in% excluded)]
  mutate_at(x, included, ~replace_na(., 0))
})
```

```{r locality covariates}
localities <- read_csv(here("data", "localities.csv")) 
filter(localities, is.na(age.at.registration))
HåkøyaAge <- localities %>% 
  filter(species == "P.sitchensis-lutz", county %in% c("Troms","Nordland")) %>% 
  pull(age.at.registration) %>% 
  mean(na.rm = TRUE) %>% 
  round()
localities <- mutate(localities, age.at.registration = case_when(
  locality == "Håkøya" & species == "P.sitchensis-lutz" ~ HåkøyaAge,
  TRUE ~ age.at.registration
))

localities <- localities %>% 
  select(locality, species, age.at.registration, utm33.easting, utm33.northing) %>% 
  st_as_sf(coords=c("utm33.easting", "utm33.northing")) %>% 
  st_set_crs(25833) %>% 
  as("Spatial")

chelsa <- raster::stack(here("data","raw","CHELSA","CHELSA_bio_1.tif"),
                        here("data","raw","CHELSA","CHELSA_bio_19.tif"))
jointable <- raster::extract(chelsa, localities, sp = TRUE) %>% 
  st_as_sf() %>% st_set_geometry(NULL) %>% as_tibble() %>% 
  rename(age = age.at.registration, bio01 = CHELSA_bio_1, bio19 = CHELSA_bio_19) %>% 
  mutate(locality = tolower(locality))
anyNA(jointable)

percell.agg <- percell.agg %>% 
  map_dfr(identity, .id = 'species') %>% 
  left_join(jointable, by = c("species", "locality")) %>%
  select(species, locality, wildlings, age, bio01, bio19, 
         seeds.ExP, seeds.WALD, relelev, `plantation forest`, everything()) %>% 
  group_split(species, keep = TRUE)
names(percell.agg) <- map_chr(percell.agg, ~pull(., species) %>% unique())

str(map(percell, ~ map_dfr(., identity, .id = "locality")), 1)
str(percell.agg, 1)

saveRDS(percell.agg, here("output","data.rds"))
```

```{r sessionInfo}
sessionInfo()
```