---
title: "Manuscript figures"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(patchwork)
library(ggtext)
library(here)
library(sf)
library(rnaturalearth)
```

# Sites map

```{r, eval=FALSE}
ne_download(scale = 50, type = 'populated_places', category = 'cultural', 
            destdir = here("data", "raw", "cartographic"), load = FALSE)
ne_download(scale = 10, type = 'minor_islands', category = 'physical', 
            destdir = here("data", "raw", "cartographic"), load = FALSE)
```

```{r}
cities <- ne_load(scale = 50, type = 'populated_places', category = 'cultural', 
                  destdir = here("data", "raw", "cartographic"), returnclass = 'sf')
norcities <- filter(cities, NAME %in% c("Oslo", "Trondheim", "Bergen"))
norislands <- ne_load(scale = 10, type = 'minor_islands', category = 'physical', 
                destdir = here("data", "raw", "cartographic"), returnclass = 'sf') %>% 
  st_crop(xmin = 4, xmax = 32, ymin = 58, ymax = 72) %>% 
  st_transform(crs = 25833) # ETRS89 / UTM zone 33N

nor50 <- ne_countries(scale = 50, country = c("Norway"), returnclass = "sf") %>% 
  st_transform(crs = 25833)
nor10 <- ne_countries(scale = 10, country = "Norway", returnclass = "sf") %>% 
  st_transform(crs = 25833)

locs <- read_csv(here("data", "localities.csv"), col_types = cols()) %>% 
  st_as_sf(coords=c("utm33.easting", "utm33.northing"), crs = 25833)
locs <- mutate(locs, species.latin = factor(species.latin, 
                                            levels = c("Picea sitchensis / lutzii",
                                                       "Picea abies",
                                                       "Larix spp.",
                                                       "Pinus contorta")))
st_bbox(locs)

filter(locs, county %in% c("Rogaland","Hordaland")) %>% 
  st_bbox()
xlimits <- c(-69e3,10e3)
ylimits <- c(6.515e6,6.775e6)
inset <- st_polygon(list(matrix(c(xlimits[1],ylimits[1],
                         xlimits[2],ylimits[1],
                         xlimits[2],ylimits[2],
                         xlimits[1],ylimits[2],
                         xlimits[1],ylimits[1]), byrow = T, ncol = 2))) %>% 
  st_sfc(crs = 25833)

filter(locs, year.registered == 2019) %>% 
  st_bbox()
xlimits2 <- c(362e3,430e3)
ylimits2 <- c(7.255e6,7.355e6)
inset2 <- st_polygon(list(matrix(c(xlimits2[1],ylimits2[1],
                         xlimits2[2],ylimits2[1],
                         xlimits2[2],ylimits2[2],
                         xlimits2[1],ylimits2[2],
                         xlimits2[1],ylimits2[1]), byrow = T, ncol = 2))) %>% 
  st_sfc(crs = 25833)

g1 <- ggplot() +
  geom_sf(data = nor50, fill = "white") + 
  geom_sf(data = norcities) +
  geom_sf_text(data = norcities, aes(label = NAME), 
               nudge_y = c(-3e4,3e4,4e4), 
               nudge_x = c(0, 10e4, 0), size = 2) +
  geom_sf(data = locs, #st_jitter(locs, amount=5e3)
          mapping = aes(color = species.latin, shape = species.latin), 
          show.legend = "point", size = 1.5, alpha = 0.6) +
  scale_shape_manual(values = c(15, 16, 17, 18)) +
  geom_sf(data = inset, fill = NA, linetype = "longdash", color = 'black') + 
  geom_sf(data = inset2, fill = NA, linetype = "longdash", color = 'black') + 
  scale_color_manual(values = c('#984ea3','#377eb8','#4daf4a','#e41a1c')) + #Set1
  coord_sf(xlim = c(-60e3,730e3), ylim = c(6.5e6,7.8e6)) +
  theme_minimal() +
  theme(legend.position = c(0.35,0.88), legend.title = element_blank(), 
        legend.text = element_text(face = "italic"),
        axis.title.x=element_blank(), axis.title.y=element_blank(),
        panel.background = element_rect(fill = "ghostwhite"))

g2 <- ggplot() +
  geom_sf(data = nor10, fill = "white") + 
  geom_sf(data = norislands, fill = "white") + 
  geom_sf(data = norcities) +
  geom_sf(data = locs, 
          mapping = aes(color = species.latin, shape = species.latin), 
          show.legend = FALSE, size = 2, alpha = 0.7) + 
  scale_shape_manual(values = c(15, 16, 17, 18)) +
  scale_color_manual(values = c('#984ea3','#377eb8','#4daf4a','#e41a1c')) + #Set1
  coord_sf(xlim = xlimits, ylim = ylimits, datum = NA) +
  theme_minimal() +
  theme(plot.margin = margin(0, 0, 0, 0),
        panel.border = element_rect(fill = NA, size=1),
        panel.background = element_rect(fill = "ghostwhite"))

g3 <- ggplot() +
  geom_sf(data = nor10, fill = "white") + 
  geom_sf(data = norislands, fill = "white") + 
  geom_sf(data = locs, 
          mapping = aes(color = species.latin, shape = species.latin), 
          show.legend = FALSE, size = 2, alpha = 0.7) + 
  scale_shape_manual(values = c(15, 16, 17, 18)) +
  scale_color_manual(values = c('#984ea3','#377eb8','#4daf4a','#e41a1c')) + #Set1
  coord_sf(xlim = xlimits2, ylim = ylimits2, datum = NA) +
  theme_minimal() +
  theme(plot.margin = margin(0, 0, 0, 0),
        panel.border = element_rect(color = "black", fill = NA, size=1),
        panel.background = element_rect(fill = "ghostwhite"))

scalefactor <- 3.6
g2x <- diff(xlimits)
g2y <- diff(ylimits)
ggplot_build(g1)$layout$coord$limits
xmax <- 750e3
ymin <- 6.45e6
g12 <- g1 + 
  annotation_custom(ggplotGrob(g2), 
                    xmin = xmax - scalefactor*g2x, xmax = xmax, 
                    ymin = ymin, ymax = ymin + scalefactor*g2y) +
  annotate("segment", linetype = "dotted",
           x = xlimits[2], xend = xmax - scalefactor*g2x, 
           y = ylimits[1], yend = ymin)
  
g2x <- diff(xlimits2)
g2y <- diff(ylimits2)
st_bbox(locs)
xmin <- -80e3
ymin <- 7.11e6
g123 <- g12 + 
  annotation_custom(ggplotGrob(g3), 
                                xmin = xmin, xmax = xmin + scalefactor*g2x, 
                                ymin = ymin, ymax = ymin + scalefactor*g2y) +
  annotate("segment", linetype = "dotted",
           x = xlimits2[1], xend = xmin + scalefactor*g2x, 
           y = ylimits2[2], yend = ymin + scalefactor*g2y)
```

```{r}
ggsave(g123, filename = 'sites-map.svg', path = here('ms', 'figures'),
  scale = 1, width = 74, height = 105, units = 'mm', dpi = 300)
```

# Site example

Criteria for selecting example location:

- Sitka spruce
- Has mosaic types
- Sources mapped outside 500x500 m

Of those locations that fill these criteria, chose that with most wildlings: Meaasen (2019).

```{r}
plotting <- readRDS(here("output","percell-data.rds"))
meaasen <- plotting$`P.sitchensis-lutzii`$meaasen
st_bbox(meaasen)
```

```{r}
png(filename = here('ms', 'figures', 'site-example', 'wildlings.png'),
    width = 10, height = 10, units = 'cm', res = 300)
plot(meaasen["wildlings"], main = 'wildlings', 
     key.pos = 1, key.width = lcm(1.4))
dev.off()

png(filename = here('ms', 'figures', 'site-example', 'WALD.png'),
    width = 10, height = 10, units = 'cm', res = 300)
plot(meaasen["seeds.WALD"], main = 'WALD seed probability density', 
     key.pos = 1, key.width = lcm(1.4), logz = TRUE, at = c(-5,-4,-3))
dev.off()

png(filename = here('ms', 'figures', 'site-example', 'T2.png'),
    width = 10, height = 10, units = 'cm', res = 300)
plot(meaasen["T2"], main = 'open shallow-soil ground', 
     key.pos = 1, key.width = lcm(1.4), nbreaks = 6)
dev.off()

png(filename = here('ms', 'figures', 'site-example', 'T4.png'),
    width = 10, height = 10, units = 'cm', res = 300)
plot(meaasen["T4"], main = 'forest', 
     key.pos = 1, key.width = lcm(1.4), nbreaks = 6)
dev.off()
```

# Establishment

```{r}
results <- readRDS(here("output","results.rds"))
types <- read_csv(here('data', 'types.csv')) %>% 
  select(-vegheight) %>% 
  mutate(name = ifelse(category == 'wetland', paste0(paste0('*',name),'*'), name)) %>% 
  mutate(name = case_when(
    name == 'drained wetland and terrestrialized freshwater sediment' ~
      'drained wetland and<br>terrestrialized freshwater sediment',
    name == 'strongly altered ground with semi-natural grassland character' ~
      'strongly altered ground with<br>semi-natural grassland character',
    name == 'agriculturally improved grassland with semi-natural character' ~
      'agriculturally improved grassland<br>with semi-natural character',
    TRUE ~ name
  ))

arith <- results$arithmetic %>% 
  bind_rows(.id = "species") %>% 
  filter(!(n == 0 & daa < 10)) %>% 
  rename(type = nin) %>% 
  left_join(types, by = 'type') %>% 
  select(-daa, -n, -density) %>% 
  mutate(modeled = FALSE)
  
est <- results$model.preds %>% 
  bind_rows(.id = "species") %>% 
  rename(type = nin) %>% 
  left_join(types, by = 'type') %>% 
  mutate(modeled = TRUE)

dat <- bind_rows(est, arith)
dat
tail(dat)
print(filter(types, type %in% dat$type), n=31)
```

```{r}
typerank <- filter(est, is.na(locality)) %>% 
  mutate(wgt = 1/(log(ci.u) - log(ci.l))) %>% 
  group_by(species) %>% 
  group_split() %>% 
  map(~ mutate(., fit.rank = percent_rank(.data$fit))) %>% 
  bind_rows() %>% 
  group_by(type) %>% 
  summarize(rank = weighted.mean(fit.rank, wgt)) %>% 
  arrange(rank)

plot <- dat %>% 
  left_join(typerank, by = 'type') %>%
  mutate(rank = if_else(is.na(rank), -1, rank)) %>%
  mutate(name = fct_reorder(name, rank))

str(plot)
```

```{r}
csize <- 3

d <- filter(plot, species == "P.sitchensis-lutzii")
col <- '#984ea3'
g1 <- ggplot(data = d, mapping = aes(x = name)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$name) == 'forest'), linetype = "dotted") +
  geom_point(data = filter(d, modeled == TRUE, !is.na(locality)),
             mapping = aes(y = fit), color = 'grey', alpha = 0.5,
             position = position_jitter(width = 0.25, height = 0)) +
  geom_linerange(data = filter(d, modeled == TRUE, is.na(locality)),
                 mapping = aes(ymin = ci.l, ymax = ci.u), color = col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE, is.na(locality)),
             mapping = aes(y = fit), color = col, size = csize) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = csize) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = c(1e-4, 1e2)) +
  labs(title = 'Picea sitchensis / lutzii', 
       x = 'ecosystem type', y = 'establishment likelihood') +
  theme_light() + 
  theme(axis.text.y = element_markdown(),
        plot.title = element_text(face = 'italic'))

d <- filter(plot, species == "P.abies")
col <- '#377eb8'
g2 <- ggplot(data = d, mapping = aes(x = name)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$name) == 'forest'), linetype = "dotted") +
  geom_point(data = filter(d, modeled == TRUE, !is.na(locality)),
             mapping = aes(y = fit), color = 'grey', alpha = 0.5,
             position = position_jitter(width = 0.25, height = 0)) +
  geom_linerange(data = filter(d, modeled == TRUE, is.na(locality)),
                 mapping = aes(ymin = ci.l, ymax = ci.u), color = col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE, is.na(locality)),
             mapping = aes(y = fit), color = col, size = csize) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = csize) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = c(1e-4, 1e2)) +
  labs(title = 'Picea abies') +
  theme_light() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(face = 'italic'))

d <- filter(plot, species == "Larix")
col <- '#4daf4a'
g3 <- ggplot(data = d, mapping = aes(x = name)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$name) == 'forest'), linetype = "dotted") +
  geom_point(data = filter(d, modeled == TRUE, !is.na(locality)),
             mapping = aes(y = fit), color = 'grey', alpha = 0.5,
             position = position_jitter(width = 0.25, height = 0)) +
  geom_linerange(data = filter(d, modeled == TRUE, is.na(locality)),
                 mapping = aes(ymin = ci.l, ymax = ci.u), color =col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE, is.na(locality)),
             mapping = aes(y = fit), color = col, size = csize) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = csize) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = c(1e-3, 1e3)) +
  labs(title = 'Larix spp.') +
  theme_light() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(face = 'italic'))

d <- filter(plot, species == "P.contorta")
col <- '#e41a1c'
g4 <- ggplot(data = d, mapping = aes(x = name)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$name) == 'forest'), linetype = "dotted") +
  geom_point(data = filter(d, modeled == TRUE, !is.na(locality)),
             mapping = aes(y = fit), color = 'grey', alpha = 0.5,
             position = position_jitter(width = 0.25, height = 0)) +
  geom_linerange(data = filter(d, modeled == TRUE, is.na(locality)),
                 mapping = aes(ymin = ci.l, ymax = ci.u), color = col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE, is.na(locality)),
             mapping = aes(y = fit), color = col, size = csize) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = csize) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = c(1e-2, 1e4)) +
  labs(title = 'Pinus contorta') +
  theme_light() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(face = 'italic'))

g1234 <- g1 + g2 + g3 + g4 + 
  plot_layout(ncol = 4)
```

```{r}
ggsave(g1234, filename= 'ggplot.svg', 
       path = here('ms', 'figures', 'establishment'),
       scale = 1, width = 29.7, height = 21, units = 'cm', dpi = 300)
```

```{r, include=FALSE}
results_sens <- readRDS(here("output","results-sensitivity.rds"))
sens <- results_sens %>% 
  bind_rows(.id = "species") %>% 
  rename(type = nin, fit.end = fit)
plot <- filter(plot, modeled, is.na(locality)) %>% 
  left_join(sens) %>% 
  mutate(diff = fit.end - fit)

d <- filter(plot, species == "P.sitchensis-lutzii")
col <- '#984ea3'
g1 <- ggplot(data = d, mapping = aes(x = name)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$name) == 'forest'), linetype = "dotted") +
  geom_segment(data = filter(d, diff != 0), 
               mapping = aes(xend = name, y = fit, yend = fit.end), color = col, 
               size = 2, lineend = 'round', linejoin = 'mitre',
               arrow = arrow(length = unit(0.001, "npc"), angle = 45, type = "closed")) +
  geom_point(data = filter(d, modeled == TRUE, is.na(locality), diff == 0),
             mapping = aes(y = fit), color = col, size = 2) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = c(1e-4, 1e2)) +
  labs(title = 'Picea sitchensis / lutzii', 
       x = 'ecosystem type', y = 'establishment likelihood') +
  theme_light() + 
  theme(axis.text.y = element_markdown(),
        plot.title = element_text(face = 'italic'))

d <- filter(plot, species == "P.abies")
col <- '#377eb8'
g2 <- ggplot(data = d, mapping = aes(x = name)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$name) == 'forest'), linetype = "dotted") +
  geom_segment(data = filter(d, diff != 0), 
               mapping = aes(xend = name, y = fit, yend = fit.end), color = col, 
               size = 2, lineend = 'round', linejoin = 'mitre',
               arrow = arrow(length = unit(0.001, "npc"), angle = 45, type = "closed")) +
  geom_point(data = filter(d, modeled == TRUE, is.na(locality), diff == 0),
             mapping = aes(y = fit), color = col, size = 2) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = c(1e-4, 1e2)) +
  labs(title = 'Picea abies', 
       x = 'ecosystem type', y = 'establishment likelihood') +
  theme_light() + 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(face = 'italic'))

d <- filter(plot, species == "Larix")
col <- '#4daf4a'
g3 <- ggplot(data = d, mapping = aes(x = name)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$name) == 'forest'), linetype = "dotted") +
  geom_segment(data = filter(d, diff != 0), 
               mapping = aes(xend = name, y = fit, yend = fit.end), color = col, 
               size = 2, lineend = 'round', linejoin = 'mitre',
               arrow = arrow(length = unit(0.001, "npc"), angle = 45, type = "closed")) +
  geom_point(data = filter(d, modeled == TRUE, is.na(locality), diff == 0),
             mapping = aes(y = fit), color = col, size = 2) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = c(1e-3, 1e3)) +
  labs(title = 'Larix spp.', 
       x = 'ecosystem type', y = 'establishment likelihood') +
  theme_light() + 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(face = 'italic'))

d <- filter(plot, species == "P.contorta")
col <- '#e41a1c'
g4 <- ggplot(data = d, mapping = aes(x = name)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$name) == 'forest'), linetype = "dotted") +
  geom_segment(data = filter(d, diff != 0), 
               mapping = aes(xend = name, y = fit, yend = fit.end), color = col, 
               size = 2, lineend = 'round', linejoin = 'mitre',
               arrow = arrow(length = unit(0.001, "npc"), angle = 45, type = "closed")) +
  geom_point(data = filter(d, modeled == TRUE, is.na(locality), diff == 0),
             mapping = aes(y = fit), color = col, size = 2) +
  scale_y_log10(
    breaks = scales::trans_breaks("log10", function(x) 10^x),
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = c(1e-2, 1e4)) +
  labs(title = 'Picea sitchensis / lutzii', 
       x = 'ecosystem type', y = 'establishment likelihood') +
  theme_light() + 
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_text(face = 'italic'))

g1234 <- g1 + g2 + g3 + g4 + 
  plot_layout(ncol = 4)

ggsave(g1234, filename= 'establishment-sensitivity-new.svg', 
       path = here('ms', 'figures'),
       scale = 1, width = 29.7, height = 21, units = 'cm', dpi = 300)
```

# Establishment hypotheses

```{r}
results.hypothesis <- readRDS(here("output","results-hypothesis.rds"))
results.hypothesis <- results.hypothesis[-3] # Removed P.contorta item (see 'reports/hypothesisComparisons.Rmd')
results.hypothesis <- map(results.hypothesis, bind_rows)

d <- map(results.hypothesis, function(x) {
  display <- filter(x, !modeled) %>% 
    group_by(structuring) %>% 
    summarize(daa = sum(daa), n = sum(n)) %>% 
    filter(daa > 10 | n > 0) %>% 
    pull(structuring)
  filter(x, modeled | structuring %in% display)
})

d <- d %>% 
  bind_rows(.id = "species") %>% 
  ungroup() %>% 
  mutate(category = case_when(
    category == 'terr' ~ 'terrestrial',
    category == 'wetl' ~ 'wetland'
  )) %>% 
  mutate(structuring = case_when(
    structuring == 'nodist' ~ 'none',
    structuring == 'stress' ~ 'environmental stress',
    structuring == 'regdist' ~ 'regulating disturbance',
    structuring == 'desdist' ~ 'destabilizing disturbance',
    structuring == 'modandist' ~ 'moderate<br>anthropogenic disturbance',
    structuring == 'strandist' ~ 'strong<br>anthropogenic disturbance'
  ))

catrank <- filter(d, modeled) %>%
  mutate(wgt = 1/(log(ci.u) - log(ci.l))) %>%
  group_by(species) %>%
  group_split() %>%
  map(~ mutate(., fit.rank = percent_rank(.data$fit))) %>%
  bind_rows() %>%
  group_by(category) %>%
  summarize(rank = weighted.mean(fit.rank, wgt)) %>%
  arrange(rank)
structrank <- filter(d, modeled) %>%
  mutate(wgt = 1/(log(ci.u) - log(ci.l))) %>%
  group_by(species) %>%
  group_split() %>%
  map(~ mutate(., fit.rank = percent_rank(.data$fit))) %>%
  bind_rows() %>%
  group_by(structuring) %>%
  summarize(rank = weighted.mean(fit.rank, wgt)) %>%
  arrange(rank)
plotd <- d %>%
  left_join(catrank, by = 'category') %>%
  mutate(category = fct_reorder(category, rank)) %>% 
  select(-rank) %>% 
  left_join(structrank, by = 'structuring') %>%
  mutate(structuring = fct_reorder(structuring, rank)) %>% 
  select(-rank)

ylimits <- plotd %>%
  pivot_longer(cols = c('fit', 'ci.l', 'ci.u'), names_to = 'what') %>%
  filter(value > 0) %>% 
  group_by(species) %>% 
  group_split() %>%
  map(~ range(pull(., value), na.rm = TRUE))
names(ylimits) <- plotd %>% 
  pull(species) %>% 
  unique()
```

```{r}
d <- filter(plotd, species == "P.sitchensis-lutzii", structuring == "none")
col <- '#984ea3'
g1 <- ggplot(data = d, mapping = aes(x = category)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$category) == 'terrestrial'), 
             linetype = "dotted") +
  geom_linerange(data = filter(d, modeled == TRUE), 
                 mapping = aes(ymin = ci.l, ymax = ci.u), color = col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE),
             mapping = aes(y = fit), color = col, size = 2) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = 2) +
  scale_y_log10(minor_breaks = NULL) +
  coord_flip(ylim = ylimits$`P.sitchensis-lutzii`) +
  labs(title = 'Picea sitchensis / lutzii',  x = 'ecosystem\ncategory') +
  theme_light() + 
  theme(axis.text.y = element_markdown(),
        plot.title = element_text(face = 'italic'),
        axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x = element_blank()) 

d <- filter(plotd, species == "P.abies", structuring == "none")
col <- '#377eb8'
g2 <- ggplot(data = d, mapping = aes(x = category)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$category) == 'terrestrial'), 
             linetype = "dotted") +
  geom_linerange(data = filter(d, modeled == TRUE), 
                 mapping = aes(ymin = ci.l, ymax = ci.u), color = col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE),
             mapping = aes(y = fit), color = col, size = 2) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = 2) +
  scale_y_log10(minor_breaks = NULL) +
  coord_flip(ylim = ylimits$P.abies) +
  labs(title = 'Picea abies') +
  theme_light() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x = element_blank(),
        plot.title = element_text(face = 'italic'))

d <- filter(plotd, species == "Larix", structuring == "none")
col <- '#4daf4a'
g3 <- ggplot(data = d, mapping = aes(x = category)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$category) == 'terrestrial'), 
             linetype = "dotted") +
  geom_linerange(data = filter(d, modeled == TRUE), 
                 mapping = aes(ymin = ci.l, ymax = ci.u), color = col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE),
             mapping = aes(y = fit), color = col, size = 2) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = 2) +
  scale_y_log10(minor_breaks = NULL) +
  coord_flip(ylim = ylimits$Larix) +
  labs(title = 'Larix spp.') +
  theme_light() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x = element_blank(),
        plot.title = element_text(face = 'italic'))

d <- filter(plotd, species == "P.sitchensis-lutzii", category == "terrestrial")
col <- '#984ea3'
g5 <- ggplot(data = d, mapping = aes(x = structuring)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$structuring) == 'none'), 
             linetype = "dotted") +
  geom_linerange(data = filter(d, modeled == TRUE), 
                 mapping = aes(ymin = ci.l, ymax = ci.u), color = col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE),
             mapping = aes(y = fit), color = col, size = 2) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = 2) +
  scale_y_log10(
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = ylimits$`P.sitchensis-lutzii`) +
  labs(x = 'ecosystem\nstructuring', y = 'establishment likelihood') +
  theme_light() + 
  theme(axis.text.y = element_markdown(),
        plot.title = element_blank())

d <- filter(plotd, species == "P.abies", category == "terrestrial")
col <- '#377eb8'
g6 <- ggplot(data = d, mapping = aes(x = structuring)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$structuring) == 'none'), 
             linetype = "dotted") +
  geom_linerange(data = filter(d, modeled == TRUE), 
                 mapping = aes(ymin = ci.l, ymax = ci.u), color = col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE),
             mapping = aes(y = fit), color = col, size = 2) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = 2) +
  scale_y_log10(
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = ylimits$P.abies) +
  theme_light() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_blank())

d <- filter(plotd, species == "Larix", category == "terrestrial")
col <- '#4daf4a'
g7 <- ggplot(data = d, mapping = aes(x = structuring)) + 
  scale_x_discrete(drop = FALSE) +
  geom_vline(xintercept = which(levels(d$structuring) == 'none'), 
             linetype = "dotted") +
  geom_linerange(data = filter(d, modeled == TRUE), 
                 mapping = aes(ymin = ci.l, ymax = ci.u), color = col, size = 1) +
  geom_point(data = filter(d, modeled == TRUE),
             mapping = aes(y = fit), color = col, size = 2) +
  geom_point(data = filter(d, modeled == FALSE), mapping = aes(y = fit), 
             color = col, pch = 1, size = 2) +
  scale_y_log10(
    labels = scales::trans_format("log10", scales::math_format(10^.x)),
    minor_breaks = NULL) +
  coord_flip(ylim = ylimits$Larix) +
  theme_light() +
  theme(axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        axis.title.x = element_blank(),
        plot.title = element_blank())

g <- 
  g1 + g2 + g3 + 
  g5 + g6 + g7 +
  plot_layout(ncol = 3, heights = c(2, 6))
```

```{r}
ggsave(g, filename= 'establishment-hypotheses.svg', path = here('ms', 'figures'),
  scale = 1.5, width = 150, height = 297/5, units = 'mm', dpi = 300)
```


# sessionInfo 

```{r sessionInfo}
sessionInfo()
```