---
title: "Manuscript tables"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
```

# Correlations between surveyed and modelled abundance

```{r}
results.models <- readRDS(here("output","results-models.rds"))
results.densities <- readRDS(here("output","results-densities.rds"))

mod <- results.models %>% 
  filter(is.na(hgtclass) | (hgtclass == 2 & randomseed == 2)) %>% 
  select(-data, -model) %>% 
  unnest(preds) %>% 
  filter(is.na(locality)) %>% 
  select(species, nin, fit, hgtclass) %>% 
  mutate(modeled = TRUE)
dens <- results.densities %>% 
  filter(is.na(hgtclass) | (hgtclass == 2 & randomseed == 2)) %>% 
  unnest(density) %>% 
  filter(!(n == 0)) %>% 
  select(species, nin, fit, hgtclass) %>% 
  mutate(modeled = FALSE)
tabling <- bind_rows(dens, mod)
```

```{r}
op <- par(mfrow = c(2,3))
tabling %>% 
  pivot_wider(names_from = modeled, values_from = fit, names_prefix = 'modeled') %>% 
  group_by(species, hgtclass) %>%
  group_split() %>% 
  walk(\(x) plot(x$modeledFALSE, x$modeledTRUE))
par <- op   
out <- tabling %>% 
  pivot_wider(names_from = modeled, values_from = fit, names_prefix = 'modeled') %>% 
  group_by(species, hgtclass) %>%
  summarise(pearson = cor(modeledTRUE, modeledFALSE),
            spearman = cor(modeledTRUE, modeledFALSE, method = "spearman"),
            .groups = "drop")
out
write_csv(out, here('ms', 'tables', 'corr-between-estimates.csv'))
```

```{r, include = FALSE}
#Reference type doesn't matter:
a <- c(1,3,5)
b <- c(1,7,9)
cor(a, b, method="pearson") == cor(a/3, b/7, method="pearson")
```

# Correlations between species in establishment

```{r}
d <- tabling %>% 
  filter(modeled) %>% 
  select(-modeled) %>% 
  pivot_wider(names_from = species, values_from = fit) %>% 
  group_by(hgtclass) %>%
  group_split() %>% 
  set_names(nm = c('2', 'NA'))

walk2(d, names(d), \(x, y) select(x, -nin, -hgtclass) %>% 
        pairs(main = paste("hgtclass", y)))
walk2(d, names(d), \(x, y) select(x, P.abies, Larix) %>% 
        na.omit() %>% 
        pairs(main = paste("hgtclass", y)))

pearson <- d %>% 
  map(\(x) select(x, `P.sitchensis-lutzii`, P.abies, Larix) %>% 
        cor(use = "pairwise.complete.obs", method = c("pearson")) %>% 
        as_tibble(rownames = 'species1') %>% 
        pivot_longer(cols = !species1, names_to = 'species2', values_to = 'pearson')) %>% 
  bind_rows(.id = 'hgtclass')
spearman <- d %>% 
  map(\(x) select(x, `P.sitchensis-lutzii`, P.abies, Larix) %>% 
        cor(use = "pairwise.complete.obs", method = c("spearman")) %>% 
        as_tibble(rownames = 'species1') %>% 
        pivot_longer(cols = !species1, names_to = 'species2', values_to = 'spearman')) %>% 
  bind_rows(.id = 'hgtclass')
out <- full_join(pearson, spearman)

out %>% 
  filter(species1 != species2) %>% 
  mutate(combo = paste(pmax(species1, species2), pmin(species1, species2))) %>% 
  distinct(hgtclass, combo, .keep_all = TRUE) %>% 
  select(-combo)

write.csv(out, here('ms', 'tables', 'corr-between-species.csv'), row.names = TRUE)
```

# Model comparisons

```{r}
modelcomp <- results$model.comp %>% 
  set_names(c("Picea sitchensis / lutzii", "Picea abies", "Larix spp.", "Pinus contorta")) %>% 
  bind_rows(.id = "species group") %>% 
  mutate(`seed dispersal estimate` = ifelse(`seed dispersal estimate` == "ExP",
                                            "Exponential Power",
                                            `seed dispersal estimate`))
write.csv(modelcomp, here('ms', 'tables', 'modelcomp.csv'), row.names = FALSE)
```

# Model summaries

```{r}
Psmod <- results$models$`P.sitchensis-lutzii`
Nre <- Psmod$modelInfo$reStruc$condReStruc$`1 | locality`$blockReps
Ps.tidy <- broom.mixed::tidy(Psmod)
Ps <- Ps.tidy %>% 
  arrange(component) %>% 
  mutate(component = if_else(component == 'cond', 
                             'Conditional Model', 
                             'Zero-inflation model')) %>% 
  mutate(ci.l = estimate - 1.96*std.error, ci.u = estimate + 1.96*std.error) %>% 
  mutate_if(is.double, ~ round(., digits = 2)) %>% 
  mutate(`95% CI` = if_else(is.na(std.error), NA_character_, 
                            paste0(ci.l, ', ', ci.u))) %>% 
  mutate(`SD (Intercept)` = if_else(effect == 'fixed', NA_real_, estimate),
         estimate = if_else(effect == 'fixed', estimate, NA_real_),
         N = if_else(effect == 'fixed', NA_real_, Nre),
         term = if_else(effect == 'fixed', term, 'locality')) %>% 
  select(`Mixture component` = component, Term = term, Estimate = estimate, 
         `95% CI`, `SD (Intercept)`, N)
write_csv(Ps, here('ms', 'tables', 'Ps-modelsummary.csv'))

Pamod <- results$models$P.abies
Nre <- Pamod$modelInfo$reStruc$condReStruc$`1 | locality`$blockReps
Pa.tidy <- broom.mixed::tidy(Pamod)
Pa <- Pa.tidy %>% 
  arrange(component) %>% 
  mutate(component = if_else(component == 'cond', 
                             'Conditional Model', 
                             'Zero-inflation model')) %>% 
  mutate(ci.l = estimate - 1.96*std.error, ci.u = estimate + 1.96*std.error) %>% 
  mutate_if(is.double, ~ round(., digits = 2)) %>% 
  mutate(`95% CI` = if_else(is.na(std.error), NA_character_, 
                            paste0(ci.l, ', ', ci.u))) %>% 
  mutate(`SD (Intercept)` = if_else(effect == 'fixed', NA_real_, estimate),
         estimate = if_else(effect == 'fixed', estimate, NA_real_),
         N = if_else(effect == 'fixed', NA_real_, Nre),
         term = if_else(effect == 'fixed', term, 'locality')) %>% 
  select(`Mixture component` = component, Term = term, Estimate = estimate, 
         `95% CI`, `SD (Intercept)`, N)
write_csv(Pa, here('ms', 'tables', 'Pa-modelsummary.csv'))

Lmod <- results$models$Larix
Nre <- Lmod$modelInfo$reStruc$condReStruc$`1 | locality`$blockReps
L.tidy <- broom.mixed::tidy(Lmod)
L <- L.tidy %>% 
  arrange(component) %>% 
  mutate(component = if_else(component == 'cond', 
                             'Conditional Model', 
                             'Zero-inflation model')) %>% 
  mutate(ci.l = estimate - 1.96*std.error, ci.u = estimate + 1.96*std.error) %>% 
  mutate_if(is.double, ~ round(., digits = 2)) %>% 
  mutate(`95% CI` = if_else(is.na(std.error), NA_character_, 
                            paste0(ci.l, ', ', ci.u))) %>% 
  mutate(`SD (Intercept)` = if_else(effect == 'fixed', NA_real_, estimate),
         estimate = if_else(effect == 'fixed', estimate, NA_real_),
         N = if_else(effect == 'fixed', NA_real_, Nre),
         term = if_else(effect == 'fixed', term, 'locality')) %>% 
  select(`Mixture component` = component, Term = term, Estimate = estimate, 
         `95% CI`, `SD (Intercept)`, N)
write_csv(L, here('ms', 'tables', 'L-modelsummary.csv'))

Pcmod <- results$models$P.contorta
Nre <- Pcmod$modelInfo$reStruc$condReStruc$`1 | locality`$blockReps
Pc.tidy <- broom.mixed::tidy(Pcmod)
Pc <- Pc.tidy %>% 
  arrange(component) %>% 
  mutate(component = if_else(component == 'cond', 
                             'Conditional Model', 
                             'Zero-inflation model')) %>% 
  mutate(ci.l = estimate - 1.96*std.error, ci.u = estimate + 1.96*std.error) %>% 
  mutate_if(is.double, ~ round(., digits = 2)) %>% 
  mutate(`95% CI` = if_else(is.na(std.error), NA_character_, 
                            paste0(ci.l, ', ', ci.u))) %>% 
  mutate(`SD (Intercept)` = if_else(effect == 'fixed', NA_real_, estimate),
         estimate = if_else(effect == 'fixed', estimate, NA_real_),
         N = if_else(effect == 'fixed', NA_real_, Nre),
         term = if_else(effect == 'fixed', term, 'locality')) %>% 
  select(`Mixture component` = component, Term = term, Estimate = estimate, 
         `95% CI`, `SD (Intercept)`, N)
write_csv(Pc, here('ms', 'tables', 'Pc-modelsummary.csv'))
```

# Types by report

```{r}
locs <- read_csv(here('data', 'localities.csv')) # see 'wildlings-NiN.Rmd'
locs <- select(locs, reference, locality, species) %>% 
  mutate(locality = tolower(locality))

datlist <- readRDS(here("output","data.rds"))
dat <- bind_rows(datlist, .id = "species") %>% 
  select(-c(age, bio01, bio19, seeds.ExP, seeds.WALD, relelev, `plantation forest`))

d <- full_join(locs, dat)
summbyref <- pivot_longer(d, !(1:4), names_to = "nin", values_to = "are") %>%
  group_by(species, reference, nin) %>% 
  summarize(daa = sum(are)/10, # units from are to decare
            n = sum(wildlings*are)) %>% 
  filter(n > 0)

summbytype <- summbyref %>% 
  group_by(species, nin) %>% 
  summarize(n = sum(n),
            daa = sum(daa))

summ <- summbyref %>% 
  group_by(species, nin) %>% 
  summarize(reference = reference) %>% 
  left_join(summbytype)

types <- read_csv(here('data', 'types.csv')) %>% 
  transmute(nin = type, type = name)

tab <- left_join(summ, types) %>%
  select(species, code = nin, type, wildlings = n, daa, reference) %>% 
  arrange(species, code) %>% 
  mutate(species = case_when(
    species == "P.contorta" ~ "Pinus contorta",
    species == "P.sitchensis-lutzii" ~ "Picea sitchensis / lutzii",
    species == "P.abies" ~ "Picea abies",
    species == "Larix" ~ "Larix spp.")) %>% 
  rename(`species group` = species) %>% 
  mutate(order = case_when(
    str_length(code) == 2 ~ paste0(substr(code,1,1),"0",substr(code,2,2)),
    TRUE ~ code)) %>% 
  arrange(`species group`, order) %>% 
  select(-order)
```

# sessionInfo 

```{r sessionInfo}
sessionInfo()
```