---
title: "Writing time"
output: html_notebook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Purpose, argument, questions, hypotheses

## Purpose

1. The purpose of this article is to explore why exotic conifers planted in Norway sometimes stay confined to the plantation and in other instances spread wildly to their surroundings.
1. The purpose of this article is to investigate which nature types in Norway are most susceptible to invasion by non-native tree species from forestry plantations. 
2. (The purpose of this article is to compare the invasibility of different nature types in Norway with respect to forestry species, and to highlight how the spatial arrangement of nature types around forestry plantations affects invasion risk.)

### Reflections on purpose

Patterns of observed spread from plantations vary --- both in the number of established individuals and the distance of these individuals from the plantation. Some of this variation may be tied to characteristics of the plantation itself (invasiveness sensu lato), some of it may have to do with the surroundings of the plantation (invasibility sensu lato), and some of it may may have to do with neither (stochastic/unexplained variability). Logically, management decisions for new and existing plantations are also based on plantation characteristics (e.g. species, seed production, height), as well as plantation surroundings (e.g. dispersal vectors, presence of vulnerable habitats). Stochastic variation in spread is by definition unpredictable, and therefore uninteresting for managers.

S in SUCCES: Should we black-list species or red-list what they threaten? Should invasion outcomes be attributed to the species identity or site characteristics? 
E in SUCCES: To manage an invading conifer, should we assess its invasiveness or the invasibility of the land?

Here, we examine how the surroundings of a forestry plantation affects spread of individuals by quantifying the relative probability of establishment in different nature types. Probability of establishment is by definition normalized with respect to the number of arriving propagules, and is therefore independent of the seed production and seed dispersal of the plantation. It is a quantity that results from physiological processes of seed survival, germination and growth, so we expect it to vary between nature types, and probably also between conifer species. 

The probability of spread to a particular location is a function of the propagule pressure on that location, and the rate of establishment. Propagule pressure from a local source population to a particular location can be decomposed into propagule production at the source, followed by dispersal to the location. Propagule production varies continuously (with age), and dispersal varies continuously with the effective distance to the plantation (horizontal, vertical, orientation). Rate of establishment varies with characteristics of the surroundings (vegetation, abiotic factors, etc). If the characteristics of the surroundings can be categorized into units within which establishment rate is constant, then establishment rate varies categorically with these units. *Nature types as management units in Norways and their (limited) correspondence with true ecological variation.*

However, from a cost-of-control perspective, it is not the rate of establishment that matters, but the number of trees. Also, the value of removing a tree may differ between areas, e.g. to prevent spread into protected nature. Therefore, a manager ideally wants to know how many trees will establish in a particular area over a certain time period. To calculate the number of trees, one needs both the establishment rate and the number of seeds arriving over that time period. The number of seeds arriving changes throughout the lifetime of a plantation, as seed production generally increases with age, and dispersal distance changes with height. Therefore it is hard to generalize about the number of seeds arriving. However the establishment rate is assumed to be unchanging, based on the fact that it is a function of the species characterisitics and (relatively) unchanging conditions at a particular location. 

## Arguments

Arguments underlying purpose and claims underlying arguments:

- Invasion originates from plantations (forestry and windbreak)
  + Locations of plantations are extensive if small
  + Most plantations have reached reproductive age and produce seed
  + Observed establishment of spread individuals is generally located near plantations.
- Nature types differ in their susceptibility to invasion
  + The conditions where a propagule (seed) arrives affect germination, growth, and survival
  + Nature types reflect homogenous conditions for germination, growth, and survival
- Spread risk is affected by the spatial distribution of nature types around forestry plantations. 
  + Seed dispersal is largest to the areas closest to plantations.
  + The distribution of nature types around plantations varies.
  
## Research questions + hypotheses

1. Do nature types differ in their susceptibility to invasion by non-native plantation trees? For all species?

- We hypothesize that nature types --- at least main types (hovedtyper) --- differ in their susceptibility to spread for all species.

2. Which nature types are most susceptible to invasion by non-native plantation trees? For all species?

- We hypothesize that nature types characterized by irregular disturbance events (*how often? be specific*) will show the highest susceptibility, that nature types without canopy cover will show high susceptibility, that nature types with canopy cover will show low susceptibility, and that nature types with annual human intervention will show lowest susceptibility. We also hypothesis that these differences will be greatest for species which are fast-growing and shade-intolerant.

3. Are characteristics of the plantation or characteristics of the surroundings the more important determinants of spread? Is variation in abundance of wildlings greater between sites (primarily plantation differences) or within sites (primarily nature type differences)? 

- We hypothesize that abundance of wildlings varies more between sites than between nature types, and that this variation primarily reflects species differences and differences in the seed production of the plantation (unmeasured).

4. How much variation in wildling abundance is explained by location, age, and surroundings? 

- We hypothesize that most variation remains unexplained by these factors alone. The implication is that other factors that are difficult for managers to predict, like age-independent seed production or more fine-scale differences in surroundings, strongly influence rate of spread.

# Introduction

In Norway, forestry plantations are abundant and extensive source populations of exotic conifers, and their surroundings are vulnerable to spread.


Managers are interested in limiting or eliminating spread from plantations, especially into areas with high ecological value (protected areas?).
Therefore, the key process that we examine is naturalized spread, which can be broken down into the processes of seed arrival and then germination, growth, and survival (assuming that the seed is viable when it arrives).
Seed arrival depends on disperal from source populations, and is a fundamentally spatial process. 
Meanwhile, germination, growth, and survival (hereafter: "establishment") depend on the conditions at the arrival location.
To better understand which factors govern naturalized spread, we need to know how seeds are dispersed from plantations, and which landing site conditions promote or inhibit establishment. 

Therefore, the number of wildlings in the surroundings of a plantation is a function of the seed shadow from the plantation and the environmental characteristics of the proximal area.
Note that the seed shadow is not purely a function of plantation characteristics; plantation surroundings also affect the seed shadow.  
For example, lower elevations may trap more seeds.

The degree of naturalized spread observed surrounding plantations is highly variable.
Specifically, the number of naturalized individuals, their location with respect to the plantation, and their rate of growth varies. 
Many factors may be hypothesized to affect the degree of naturalized spread: the species in the plantation, the seed production of the plantation, the dispersal capacity of the the seeds, and the establishment rate of the seeds in the surroundings.  

### Spatial scale of variation

First it is important to consider at what spatial scale variability in natural recruitment occurs. This may differ between species. If most variation occurs at the coarsest spatial scale, drivers that also vary at course scales, such as climate, are likely to be important. If variation between plantations is greater than variation between regions, climate and other coarse-scale factors are probably less important, and drivers that vary at the plantation scale are likely important. If more variation occurs around single plantations than between plantations, site characteristics (e.g. surrounding nature types) are likely the most important governing factors. 

However, there may be covariance between factors operating at different scales. For example, it could be that the plantations in Rogaland are older than the plantations in Nordland, and therefore enjoy a warmer climate and produce more seeds. Covariances between scales obscures the relative importance of regional and plantation-level factors, as collinearity does in statistical models. A similar example of this would be if highly invadable nature types occurred more frequently around plantations with high seed production. Is higher recruitment due to higher seed production or due to more invadable surroundings? None of these confounding effects can be solved in a purely observational dataset, but it is worth exploring whether they appear to be problematic. That is, one can check correlations.

If plantation-level and regional-level factors are not of interest, these can be treated as random effects in a mixed model. If they are of interest, then appropriate variables for these different scales must be identified and acquired. 

Data on plantation-level characterstics are scarce, but some may be extractable from aerial photography (density?). The most important plantation level characterisitics are seed production and seed dispersal capacity, because these two directly affect propagule pressure on the surrounding area. Seed production may be predicted by age of the plantation or height, but also varies strongly year to year.

An important critical reading question: have previous studies been able to disentangle the effect of distance to plantation from the effect of invasibility? If, for example, only one nature type occurs around each plantation, the data do not provide a basis to do that.

# Methods

### Overall conceptual model

$$(Number\; of\; individuals)_{xy} \propto (Seed\; supply)_{xy}\; * (Establishment\; rate)_{xy}$$
where xy is the location. 

Rearranged:
$$(Establishment\; rate)_{xy}  \propto \frac{(Number\; of\; individuals)_{xy}}{(Seed\; supply)_{xy}}$$
Advantage to observational study (registering established individuals rather than doing seeding plots) is that seeds experience only natural conditions, and it measures long-term survival --- the quantity of interest for management.

### Seed dispersal model

#### Sensitivity of establishment probability to seed dispersal model

There are a lot of assumptions and parameters in the anisotropic WALD seed dispersal model. For example, with regards to wind, we assume that wind data from the nearest weather station are representative for the locality, that the wind data are representative for annual period during which seeds are released, and that abscission is constant. With regards to sources, we assume that all cones are the the top of the trees, that all individuals are the same height, that all individuals produces equal numbers of seeds, and that the seed shadow of an individual is unaffected by it position in the plantation. Furthermore, with regards to the surroundings we assume flat terrain, and that surface friction is constant. The advantage of the mechanisitic model is that it can be used to predict location-specific seed dispersal a priori --- without any measurements of seed dispersal. At the same time, we do not have the data to test how much simplifying assumptions and estimated parameters bias predictions. Since the estimated establishment rate is inversely proportional to the estimated seed supply, bias in the seed dispersal model causes bias in estimates establishment probabilities. Therefore, it is worth exploring how sensitive estimated establishment probabilities are to differences in models of seed dispersal.

Phenomenological models of seed dispersal can be parameterized using the Broervika seed trap data, and compared to the predictions from the anisotropic WALD seed dispersal model. If the WALD model performs better (blind to the trap data) than the empirically parameterized phenomenological model, that is very strong evidence for its suitability. What if the empirically fitted model is much better though --- what then? Can't fit models to localities without trap data. 

Alternatively, a generalized, parameterized phenomenological model from Bullock et al. 2017 can be compared to the anisotropic WALD model using the Broervika seed trap data. This has the great advantage that the generalized phenomenological model could be applied to all localities if it was found to outperform the mechanisitic model, or both models could be used at all localities to assess the uncertainty associated with choice of dispersal model. 

Finally, the sensitivity of estimated establishment probabilities to the dispersal model can also be explored in a very simplistic way by examining establishment probabilities that assume no effect of distance to plantation. That is, establishment probability could be estimated as the number of individuals established per unit area of each nature type. The pool of area could be bounded by a simple buffer around the plantation, extending as far as the furthest wildling. 

As an aside, it is worth checking that any analysis is not limited by the size of the mapped plots (500x500 m). If a large proportion of wildlings occur outside the plots, relative establishment probabilities are subject to greater uncertainty, because that means they are inferred from a subsample of the total population of wildlings. However, a proximal subsample has no ill effects other than to reduce the size of the data set (both number of wildings and number of nature types), because we model establishment *rate*, not total establishment. A good check would be to calculate what proportion of the seed shadow (from WALD or Bullock generalized model) is within the plot.

Theoretically, the seed dispersal model could be validated by the spatial distribution of wildlings within a single nature type (at a time). However, to be a good validation data set, it would requires many wildlings in a single type, that the type is distributed over many distances and directions, and the establishment is uniform within the type. Even then, inferring dispersal from established individuals might raise flags with reviewers who are weary of survivorship bias, and not convinced that establishment is constant within the type. 

To assess sensitivity to wind assumptions: compare with isotropic WALD
To assess sensitivity to wind, friction, and source height assumptions: compare with phenomenological model from Bullock 2017.
To assess sensitivity to all dispersal kernel assumptions: compare with establishment per area.

What about elevation?

#### Seed dispersal constant over time?
If we measure establishment probability as the ratio of established individuals/number of seeds that landed in a particular location, then we have the difficult dimension of time. Plantations grow (in height and in seed production), and the seed dispersal model that we assume as the basis for out establishment probability is not constant over time. For example, if the spread of seeds is less distant in early years because the parent trees are not as tall, then the number of seeds landing in the closest locations will be proportionally higher.

One way to tackle this problem would be to adjust the number of established individuals according to their age, to get the right rate. One could calculate the establishment rate based only on the youngest individuals, because they have established form seed dispersal which can be assumed to be most like seed dispersal today --- they paint the best picture of the current situation. A big disadvantage to this method would be that it would throw out a whole bunch of data: the older individuals.

Another way to tackle the problems would be to try to adjust the number of seeds used in the calculation of establishment rate to account for changes over time. In other words, allow the seed dispersal model account for changes over time. We could make the model more complex to try to get an overall estimate for the number of seed that have landed in each location *throughout the seed producing period of the plantation*. The main differences in seed dispersal from year to year are in total production (masting) and in release height (due to vertical growth of parents). We could try to make the model account for height. We could for example estimate at what height the trees began producing seeds, how much they grew each year, and calculate annual seed dispersal estimates (for how ever many years necessary) that are then summed to obtain the overall estimate. However, it is clear the the model quickly becomes quite complex, and the number of assumptions required begins too raise some suspicion (eg. start of seed production is unknown and variable, annual height growth is unknown and variable). Making the model account for annual differences in total production would be harder, due to masting.  Some years (and therefore some release heights) will have large production and some will have small. Without knowing which years were the mast years, annual time steps will not sum correctly. Masting probably makes adjusting the number of seeds infeasible, unless we have some record of relative seed production of the species each year into the past. Considering that some of these plantations are quite old, those data probably dont exist, especially not for all species. 

A different idea to account for the fact that we cannot assume identical spatial distribution of seeds over time is to look at the results of that dispersal and see if there is anything in the data to suggest that the departure from constant spatial distribution is strong enough to be worrisome. We could look at the spatial distribution of different height classes of the spread individuals. If the tallest (oldest) individuals are distributed in a way that is not significantly different than the shortest (youngest) individuals, that suggests that the seed distribution was not significantly different when the plantation began producing seeds than it is today. That would imply that the changes over time in spatial distribution of seeds are negligible. One important note about this approach is that it assumes that establishment rate has been constant for each location through the seed producing period. For example, if a disturbance 10 years ago meant that seeds in a particular area were more likely to establish there then than they are there now, then this will cause a difference in the distributions of different age classes that is not due to changes in seed dispersal but in changes to establishment probability (i.e. survivorship bias). This makes sense! We have a very simple conceptual formula for our data: (number of seeds) * (establishment rate) = (number of individuals at a location). When one of the two is known or assumed to be constant we can solve for the other; otherwise we can't.

The last idea is the simplest and should be prioritized. In fact the whole issue of the temporal dimension in the data is probably best addessed using the heights of established individuals. These heights are the only solid data we have to say something about how the situation (either seed supply or establishment rate) has changed over time. Also, keep an eye out for metadata about dramatic land use changes that could have affected establishment probability over time (e.g. cessation of grazing). 

#### Relative or absolute establishment probabilities?

We must decide whether we will model establishment probabilities in nature types as relative or absolute rates. In either case the establishment probability has the same units (established wildlings per number of seeds; see overall model), but determining the absolute rate requires that we know the seed supply absolutely and not just relatively. This is parallel to knowling the total population size to determine absolute presence probability in distribution models. Do we knoww the total population size (the number of seeds produced by seed sources over the lifetime of the plantation)? Since the total seed production Q is just a constant, and otherwise has no effect on the modeling, it is easy to produce a confidence interval of absolute establishment probabilities based on relative establishment probabilities. Say that establishment probability is models with an estimated seed production of 1e6 per source, and nature type A has a rate of 1 wildling/1000 seeds; if actual total seed production is estimated to be 1e7 per source, then the absolute rate becomes 0.1 wildling/1000 seeds. What about interval estimates? Rate of [0.5,3] wildlings/1000 seeds and total production between 1e5 and 1e7 seeds per source. How does one propagate error? 